[package]
name = "createpy"
version = "1.0.19"
edition = "2021"

[dependencies]
clap = "4.4.18"
colored = "2.1.0"

[profile.dev]
opt-level = "z"
codegen-units = 1

[profile.release]
opt-level = "z"
strip = true
codegen-units = 1
